### ISSUE TITLE
es报错

### ISSUE THREAD

**Issue by boomballa** [arkcontrol/arkcontrol#7]
es直接初始化安装报错：
shell#  ./deploy-server 
INFO[0000] [sh -c \cp -rf ./nginx.conf ./nginx-1.8.0/nginx_conf/conf/] 
INFO[0000]                                               source="services/service.go:330"
INFO[0000] start nginx                                   source="services/service.go:411"
INFO[0003] Please access http://172.16.3.95:90           source="main/main.go:282"
INFO[0083] {Id:0 ServerIP:172.16.3.95 ServerPort:8090 IsInstallDB:true DBIP:172.16.3.95 DBPort:3316 DBUser:root DBPass:123456 IsInstallES:true ESIP: ESPort:9200 ESUser: ESPass: SourceDir:/ark AgentUser:ark AgentPass:123456 CreateTime:}  source="main/main.go:59"
INFO[0083] Init acme start                               source="services/service.go:224"
INFO[0083] download file ok!                             source="services/service.go:228"
INFO[0083] [sh -c tar -zxvf ./download/arkcontrol_resource.tar.gz -C ./download] 
INFO[0086] install mysql start                           source="services/service.go:250"
INFO[0086] MySQL already exist: {0 172.16.3.95 8090 true 172.16.3.95 3316 root 123456 true  9200   /ark ark 123456 }  source="services/service.go:178"
INFO[0086] install mysql success                         source="services/service.go:254"
INFO[0086] [sh -c /data/ark/arkdb/cellar/mysql57/bin/mysql -h172.16.3.95 -P3316 -uroot -p123456 < ./download/init.sql] 
INFO[0086] write config success!                         source="services/service.go:264"
ERRO[0086] init system properties failed, exit status 255  source="es/step.go:41"
ERRO[0086] es deploy: exit status 255                    source="monitor/deploy.go:22"
ERRO[0086] exit status 255                               source="services/service.go:232"
INFO[0086] [sh -c ./nginx-1.8.0/nginx_conf/sbin/nginx -p ./nginx-1.8.0/nginx_conf/ -s stop] 
INFO[0086] http: Server closed                           source="main/main.go:284"
INFO[0086] done                                          source="main/main.go:286"

![image](https://user-images.githubusercontent.com/8543659/46136443-2f4a5780-c27a-11e8-82f8-2478f04c4444.png)

所以我自己安装了es，并且关了xpack插件，重新安装：
![image](https://user-images.githubusercontent.com/8543659/46136805-fc549380-c27a-11e8-98f1-9b0bbe540bce.png)

![image](https://user-images.githubusercontent.com/8543659/46136767-ee9f0e00-c27a-11e8-840a-56b989880bb4.png)

es错误日志信息：
[2018-09-27T17:27:18,410][DEBUG][o.e.a.a.i.t.p.TransportPutIndexTemplateAction] [wl3GU6n] failed to put template [ark_monitor]
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_default_]: Could not convert [value.index] to boolean
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:317) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:279) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.validateAndAddTemplate(MetaDataIndexTemplateService.java:255) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.access$300(MetaDataIndexTemplateService.java:65) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService$2.execute(MetaDataIndexTemplateService.java:175) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:268) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) [elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) [elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.4.1.jar:6.4.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Could not convert [value.index] to boolean
	at org.elasticsearch.common.xcontent.support.XContentMapValues.nodeBooleanValue(XContentMapValues.java:433) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.TypeParsers.nodeBooleanValue(TypeParsers.java:59) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.TypeParsers.parseField(TypeParsers.java:232) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.NumberFieldMapper$TypeParser.parse(NumberFieldMapper.java:149) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:278) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:199) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:131) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:112) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:78) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:315) ~[elasticsearch-6.4.1.jar:6.4.1]
	... 17 more
Caused by: java.lang.IllegalArgumentException: Failed to parse value [no] as only [true] or [false] are allowed.
	at org.elasticsearch.common.Booleans.parseBoolean(Booleans.java:73) ~[elasticsearch-core-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.xcontent.support.XContentMapValues.nodeBooleanValue(XContentMapValues.java:438) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.common.xcontent.support.XContentMapValues.nodeBooleanValue(XContentMapValues.java:431) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.TypeParsers.nodeBooleanValue(TypeParsers.java:59) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.TypeParsers.parseField(TypeParsers.java:232) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.NumberFieldMapper$TypeParser.parse(NumberFieldMapper.java:149) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:278) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:199) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:131) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:112) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:78) ~[elasticsearch-6.4.1.jar:6.4.1]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:315) ~[elasticsearch-6.4.1.jar:6.4.1]
	... 17 more

请问这个怎么解决？

**Comment by ark-cloud** [comment]
应该是es版本问题，不好意思，6.X的es之前没有测试，看日志应该是设置index的template的参数识别不了，推荐使用5.6的版本。

看到您之前安装时候的报错init system properties failed，这个 https://github.com/arkcontrol/arkcontrol/wiki/FAQ 中有解决方案，应该是机器上的配置文件中的某些字段识别不了

**Comment by boomballa** [comment]
我装上了5.6.11，然后又报了这个错: 

![image](https://user-images.githubusercontent.com/8543659/46141159-b51fd000-c285-11e8-9b2d-dd78dee4b75b.png)

![image](https://user-images.githubusercontent.com/8543659/46141252-f617e480-c285-11e8-9589-7aca2bf9493e.png)

**Comment by ark-cloud** [comment]
这个是版本判断时，代码引起的bug，最新版本已修复，今晚（2018-09-27）会更新最新版本（v0.82），请稍后下载测试
